### ISSUE TITLE
Detail Example

### ISSUE THREAD

**Issue by gurodriguez** [PabloAlmonte/loopback-component-relation-filter#1] opened 2020-02-17 18:29 UTC
Hi, I had installed the plugin but I couldn't use it , I enable my model with this.

`  "name": "Negocios",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true,
    "relationFilter": {
      "enabled": true
    }
  }
...
"relations": {

    "negocioCategorias": {
      "type": "hasMany",
      "model": "NegocioCategorias",
      "foreignKey": "idNegocio"
    }
    
  }
}`

and  I tried  a GET request using a filter in the Loopback API explorer like this:
`{"where":{"negocioCategorias":{"idCategNegocio":34}}}`

but it still not working, it return all the rows in the table. My Database is in PostgreSQL

 Can you help me please ? What am I doing wrong?

Thanks

**Comment by PabloAlmonte** [comment] 2020-02-17 18:34
check if configuraste component in the file component-config

**Comment by gurodriguez** [comment] 2020-02-17 18:37
> check if configuraste component in the file component-config

Yes, my component-config.js file looks like :
`{
  "loopback-component-explorer": {
    "mountPath": "/explorer",
    "generateOperationScopedModels": true,
    "loopback-component-relation-filter": {
      "enabled": true
  }
  }
}`

**Comment by PabloAlmonte** [comment] 2020-02-17 18:37
```
{
    "loopback-component-relation-filter": {
        "enabled": true
    }
}
```
Please enter at least that code in the component-config.

**Comment by gurodriguez** [comment] 2020-02-17 18:40
> ```
> {
>     "loopback-component-relation-filter": {
>         "enabled": true
>     }
> }
> ```
> 
> Please enter at least that code in the component-config.

Yes, My component-config has that line of code.

**Comment by PabloAlmonte** [comment] 2020-02-17 18:44
the problem is due to your relationship, in almost that a Negocio owned or have a categoria, the relationship type should be, hasOne or belongTo. not hasMany, this is the error.

**Comment by PabloAlmonte** [comment] 2020-02-17 18:45
change the relationship type you have and you will see that it works

**Comment by gurodriguez** [comment] 2020-02-17 18:56
> change the relationship type you have and you will see that it works

I changed that and still not working  this si my full negocio-categorias.json
`{
  "name": "NegocioCategorias",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "postgresql": {
    "schema": "public",
    "table": "negocio_categorias"
  },
  "properties": {
    "id": {
      "type": "Number",
      "id": true,
      "required": false,
      "length": null,
      "precision": null,
      "scale": 0,
      "postgresql": {
        "columnName": "id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": 0,
        "nullable": "NO"
      },
      "_selectable": false
    },
    "idNegocio": {
      "type": "Number",
      "required": true,
      "length": null,
      "precision": null,
      "scale": 0,
      "postgresql": {
        "columnName": "id_negocio",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": 0,
        "nullable": "YES"
      },
      "_selectable": true
    },
    "idCategNegocio": {
      "type": "Number",
      "id": true,
      "required": true,
      "length": null,
      "precision": null,
      "scale": 0,
      "postgresql": {
        "columnName": "id_categ_negocio",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": 0,
        "nullable": "YES"
      },
      "_selectable": true
    }
  },
  "validations": [],
  "relations": {
    "categNegocios": {
      "type": "belongsTo",
      "model": "CategNegocios",
      "foreignKey": "idCategNegocio"
    },
    "negocios": {
      "type": "belongsTo",
      "model": "Negocios",
      "foreignKey": "idNegocio"
    }
  },
  "acls": [],
  "methods": {}
}
`

and the negocios.json
`
{
    "name": "Negocios",
    "base": "PersistedModel",
    "idInjection": false,
    "options": {
      "validateUpsert": true,
      "relationFilter": {
        "enabled": true
      }
    },
    "postgresql": {
      "schema": "public",
      "table": "negocios"
    },
    "properties": {
      "id": {
        "type": "Number",
        "id": true,
        "required": false,
        "length": null,
        "precision": null,
        "scale": 0,
        "postgresql": {
          "columnName": "id",
          "dataType": "integer",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": 0,
          "nullable": "NO"
        },
        "_selectable": false
      },
      "nombre": {
        "type": "String",
        "required": false,
        "length": 254,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "nombre",
          "dataType": "character varying",
          "dataLength": 254,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "descripcion": {
        "type": "String",
        "required": false,
        "length": null,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "descripcion",
          "dataType": "text",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "telefono": {
        "type": "String",
        "required": false,
        "length": null,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "telefono",
          "dataType": "text",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "direccion": {
        "type": "String",
        "required": false,
        "length": 254,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "direccion",
          "dataType": "character varying",
          "dataLength": 254,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      
      "idCiudad": {
        "type": "Number",
        "required": true,
        "length": null,
        "precision": null,
        "scale": 0,
        "postgresql": {
          "columnName": "id_ciudad",
          "dataType": "integer",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": 0,
          "nullable": "NO"
        },
        "_selectable": false
      },
      "imagen": {
        "type": "String",
        "required": false,
        "length": 254,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "imagen",
          "dataType": "character varying",
          "dataLength": 254,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      }
    },
    "validations": [],
    "relations": {
      "categoriasPertenece": {
        "type": "hasMany",
        "model": "CategNegocios",
        "foreignKey": "idNegocio",
        "through": "NegocioCategorias",
        "keyThrough": "idCategNegocio"
      },
      "ciudadPertenece": {
        "type": "belongsTo",
        "model": "CatCiudades",
        "foreignKey": "idCiudad"
      },
      "negocioCategorias": {
        "type": "hasOne",
        "model": "NegocioCategorias",
        "foreignKey": "idNegocio"
      }
    },
    "acls": [],
    "methods": {}
  }
  `

**Comment by PabloAlmonte** [comment] 2020-02-17 19:23
I think I understand which is the problem. you may have porwue the name of the column in the database, is different to the name of the property in loopback, but that's an error mine, now i'm away from the PC, but in about 2 hours actualizare the repo with this problem solved.

**Comment by gurodriguez** [comment] 2020-02-17 20:21
> I think I understand which is the problem. you may have porwue the name of the column in the database, is different to the name of the property in loopback, but that's an error mine, now i'm away from the PC, but in about 2 hours actualizare the repo with this problem solved.

Oki,   I will waiting for that. Gracias

**Comment by PabloAlmonte** [comment] 2020-02-18 16:24
Ready, the problem is already solved, you have to install version **0.1.0** from NPM and it will work correctly. Thanks for reporting the bug. Notify me if it works to close the issue

**Comment by gurodriguez** [comment] 2020-02-18 17:32
> Ready, the problem is already solved, you have to install version **0.1.0** from NPM and it will work correctly. Thanks for reporting the bug. Notify me if it works to close the issue

Hi, I made a GET request after update your library  with this filter
`{"where":{"negocioCategorias":{"idCategNegocio":34}}` 
but  I have this error 

`{
  "error": {
    "statusCode": 400,
    "name": "Error",
    "message": "No se puede analizar el valor de objeto codificado en JSON."
  }
}`

**Comment by PabloAlmonte** [comment] 2020-02-18 17:40
that error has nothing to do with the component.

**Comment by gurodriguez** [comment] 2020-02-18 18:10
> that error has nothing to do with the component.

You're right, I had a missed "  ,  but When I made a GET request again using

`{"where":{"negocioCategorias":{"idCategNegocio":34} }}`

or 
 {"where":{"negocioCategorias":{"idCategNegocio":{"identifier":34}} }}

It returns all rows, like before the bug fix.

Again this is my relation

` "negocioCategorias": {
      "type": "hasOne",
      "model": "NegocioCategorias",
      "foreignKey": "idNegocio"
    },` 

and my negocio-categorias.json 

`{
  "name": "NegocioCategorias",
  "base": "PersistedModel",
  "idInjection": false,
  "options": {
    "validateUpsert": true
  },
  "postgresql": {
    "schema": "public",
    "table": "negocio_categorias"
  },
  "properties": {
    "id": {
      "type": "Number",
      "id": true,
      "required": false,
      "length": null,
      "precision": null,
      "scale": 0,
      "postgresql": {
        "columnName": "id",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": 0,
        "nullable": "NO"
      },
      "_selectable": false
    },
    "idNegocio": {
      "type": "Number",
      "required": true,
      "length": null,
      "precision": null,
      "scale": 0,
      "postgresql": {
        "columnName": "id_negocio",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": 0,
        "nullable": "YES"
      },
      "_selectable": true
    },
    "idCategNegocio": {
      "type": "Number",
      "id": true,
      "required": true,
      "length": null,
      "precision": null,
      "scale": 0,
      "postgresql": {
        "columnName": "id_categ_negocio",
        "dataType": "integer",
        "dataLength": null,
        "dataPrecision": null,
        "dataScale": 0,
        "nullable": "YES"
      },
      "_selectable": true
    }
  },
  "validations": [],
  "relations": {
    "categNegocios": {
      "type": "belongsTo",
      "model": "CategNegocios",
      "foreignKey": "idCategNegocio"
    },
    "negocios": {
      "type": "belongsTo",
      "model": "Negocios",
      "foreignKey": "idNegocio"
    }
  },
  "acls": [],
  "methods": {}
}
`

**Comment by PabloAlmonte** [comment] 2020-02-18 18:15
let me see your negocio.json

**Comment by PabloAlmonte** [comment] 2020-02-18 18:16
what are you applying this filter to
`{"where":{"negocioCategorias":{"idCategNegocio":34} }}`

**Comment by gurodriguez** [comment] 2020-02-18 18:20
> let me see your negocio.json

my negocios.json
`{
    "name": "Negocios",
    "base": "PersistedModel",
    "idInjection": false,
    "options": {
      "validateUpsert": true,
      "relationFilter": {
        "enabled": true
      }
    },
    "postgresql": {
      "schema": "public",
      "table": "negocios"
    },
    "properties": {
      "id": {
        "type": "Number",
        "id": true,
        "required": false,
        "length": null,
        "precision": null,
        "scale": 0,
        "postgresql": {
          "columnName": "id",
          "dataType": "integer",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": 0,
          "nullable": "NO"
        },
        "_selectable": false
      },
      "nombre": {
        "type": "String",
        "required": false,
        "length": 254,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "nombre",
          "dataType": "character varying",
          "dataLength": 254,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "descripcion": {
        "type": "String",
        "required": false,
        "length": null,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "descripcion",
          "dataType": "text",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "telefono": {
        "type": "String",
        "required": false,
        "length": null,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "telefono",
          "dataType": "text",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "direccion": {
        "type": "String",
        "required": false,
        "length": 254,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "direccion",
          "dataType": "character varying",
          "dataLength": 254,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "idColonia": {
        "type": "Number",
        "required": false,
        "length": null,
        "precision": null,
        "scale": 0,
        "postgresql": {
          "columnName": "id_colonia",
          "dataType": "integer",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": 0,
          "nullable": "YES"
        },
        "_selectable": true
      },
      "idCiudad": {
        "type": "Number",
        "required": true,
        "length": null,
        "precision": null,
        "scale": 0,
        "postgresql": {
          "columnName": "id_ciudad",
          "dataType": "integer",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": 0,
          "nullable": "NO"
        },
        "_selectable": false
      },
      "imagen": {
        "type": "String",
        "required": false,
        "length": 254,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "imagen",
          "dataType": "character varying",
          "dataLength": 254,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      },    
      "activo": {
        "type": "Boolean",
        "required": false,
        "length": null,
        "precision": null,
        "scale": null,
        "postgresql": {
          "columnName": "activo",
          "dataType": "boolean",
          "dataLength": null,
          "dataPrecision": null,
          "dataScale": null,
          "nullable": "YES"
        },
        "_selectable": true
      }
    },
    "validations": [],
    "relations": {
      "categoriasPertenece": {
        "type": "hasMany",
        "model": "CategNegocios",
        "foreignKey": "idNegocio",
        "through": "NegocioCategorias",
        "keyThrough": "idCategNegocio"
      },
      "coloniaPertenece": {
        "type": "belongsTo",
        "model": "CatColonias",
        "foreignKey": "idColonia"
      },
      "ciudadPertenece": {
        "type": "belongsTo",
        "model": "CatCiudades",
        "foreignKey": "idCiudad"
      },
      "negocioCategorias": {
        "type": "hasOne",
        "model": "NegocioCategorias",
        "foreignKey": "idNegocio"
      }
    },
    "acls": [],
    "methods": {}
  }
  `
.................

Here: 
` {"where":{"negocioCategorias":{"idCategNegocio":34} }}`
I want to retrive all the negocios's rows that match  with the field id_categ_negocio in the table negocio_categorias

**Comment by PabloAlmonte** [comment] 2020-02-18 18:29
When do you include the `negocioCategoria` does it work for you?

**Comment by PabloAlmonte** [comment] 2020-02-18 18:29
Is it possible to have access to your explorer to try?

**Comment by gurodriguez** [comment] 2020-02-18 18:33
> When do you include the `negocioCategoria` does it work for you?

Yes it work, returning one row because the relation hasOne.

Is it possible to have access to your explorer to try?, it is not possible because i'm working locally on my machine.

**Comment by PabloAlmonte** [comment] 2020-02-18 18:40
> it is not possible because i'm working locally on my machine.

use this to expose your local code
https://ngrok.com/

**Comment by gurodriguez** [comment] 2020-02-18 18:58
> > it is not possible because i'm working locally on my machine.
> 
> use this to expose your local code
> https://ngrok.com/

Ok, I going to send you an email with the access

**Closed as completed** 2020-02-19 11:56 UTC
Labels: bug, good first issue
